"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Optional: Use JSON for serialization (more secure than pickle)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Task result expiration (1 hour)
CELERY_RESULT_EXPIRES = 3600

# Timezone (match Django timezone)
CELERY_TIMEZONE = "UTC"  # Or your TIME_ZONE setting
CELERY_ENABLE_UTC = True

CELERY_TASK_ROUTES = {
    "cars.tasks.*": {"queue": "cars"},  # Route car tasks to 'cars' queue
    "users.tasks.*": {"queue": "users"},
}

# Optional: Rate limiting
CELERY_TASK_ANNOTATIONS = {
    "cars.tasks.update_car_inventory": {
        "rate_limit": "10/m",  # 10 per minute
    }
}

# Optional: Task time limits
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit

# Optional: Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 4  # Tasks to prefetch
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart worker after 1000 tasks

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l!@iyn88^@@tbsk0hzo(+a3fsitv%z(=&r_%+p7q1kq6%^!ub)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
CODESPACE_NAME = os.environ.get("CODESPACE_NAME")

TRUSTED_ORIGINS = [
    "https://localhost:8000",
    "http://localhost:8000",
]
CSRF_TRUSTED_ORIGINS = TRUSTED_ORIGINS.copy()
ALLOWED_HOSTS.extend(TRUSTED_ORIGINS)
if CODESPACE_NAME:
    print(f"Running in Codespace: {CODESPACE_NAME}")
    CSRF_TRUSTED_ORIGINS.append(f"https://{CODESPACE_NAME}-8000.app.github.dev")
    ALLOWED_HOSTS.append(f"{CODESPACE_NAME}-8000.app.github.dev")
    

AWS_EC2_PUBLIC_IP = os.environ.get("EC2_PUBLIC_IP")
if AWS_EC2_PUBLIC_IP:
    print(f"Running in AWS EC2: {AWS_EC2_PUBLIC_IP}")
    ALLOWED_HOSTS.append(AWS_EC2_PUBLIC_IP)
    CSRF_TRUSTED_ORIGINS.append(f"http://{AWS_EC2_PUBLIC_IP}:8000")

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cars",
    "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["app/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = os.path.join(BASE_DIR, "media/")
MEDIA_ROOT = BASE_DIR / "media"

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
