# Generated by Django 5.2.9 on 2025-12-14 15:14

from django.db import migrations



def migrate_data(apps, schema_editor):
    Car = apps.get_model('cars', 'Car')
    Brand = apps.get_model('cars', 'Brand')
    for car in Car.objects.all():
        if car.brand:
            brand, created = Brand.objects.get_or_create(name=car.brand)
            car.brand_new = brand
            car.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_brand_new'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
