# Generated by Django 5.2.9 on 2025-12-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_migrate_brand_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='brand_new',
            new_name='brand',
        ),
    ]
