# Generated by Django 6.0.1 on 2026-01-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_car_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="plate",
            field=models.CharField(default=123456, max_length=10),
            preserve_default=False,
        ),
    ]
